// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Stonks
//
//  This is a fun Stonks service. You can find out more about us at [https://github.com/veremchukvv/stonks-test](https://github.com/veremchukvv/stonks-test).
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  License: MIT https://opensource.org/licenses/mit-license.php
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
