// Code generated by go-swagger; DO NOT EDIT.

package portfolios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeletePortfolioParams creates a new DeletePortfolioParams object
//
// There are no default values defined in the spec.
func NewDeletePortfolioParams() DeletePortfolioParams {

	return DeletePortfolioParams{}
}

// DeletePortfolioParams contains all the bound params for the delete portfolio operation
// typically these are obtained from a http.Request
//
// swagger:parameters deletePortfolio
type DeletePortfolioParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Portfolio id to delete
	  Required: true
	  In: path
	*/
	PortfolioID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeletePortfolioParams() beforehand.
func (o *DeletePortfolioParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPortfolioID, rhkPortfolioID, _ := route.Params.GetOK("portfolioId")
	if err := o.bindPortfolioID(rPortfolioID, rhkPortfolioID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPortfolioID binds and validates parameter PortfolioID from path.
func (o *DeletePortfolioParams) bindPortfolioID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("portfolioId", "path", "int64", raw)
	}
	o.PortfolioID = value

	return nil
}
