// Code generated by go-swagger; DO NOT EDIT.

package portfolios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePortfolioBadRequestCode is the HTTP code returned for type DeletePortfolioBadRequest
const DeletePortfolioBadRequestCode int = 400

/*DeletePortfolioBadRequest Invalid ID supplied

swagger:response deletePortfolioBadRequest
*/
type DeletePortfolioBadRequest struct {
}

// NewDeletePortfolioBadRequest creates DeletePortfolioBadRequest with default headers values
func NewDeletePortfolioBadRequest() *DeletePortfolioBadRequest {

	return &DeletePortfolioBadRequest{}
}

// WriteResponse to the client
func (o *DeletePortfolioBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeletePortfolioNotFoundCode is the HTTP code returned for type DeletePortfolioNotFound
const DeletePortfolioNotFoundCode int = 404

/*DeletePortfolioNotFound Portfolio not found

swagger:response deletePortfolioNotFound
*/
type DeletePortfolioNotFound struct {
}

// NewDeletePortfolioNotFound creates DeletePortfolioNotFound with default headers values
func NewDeletePortfolioNotFound() *DeletePortfolioNotFound {

	return &DeletePortfolioNotFound{}
}

// WriteResponse to the client
func (o *DeletePortfolioNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
