// Code generated by go-swagger; DO NOT EDIT.

package portfolios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPortfolioByIDHandlerFunc turns a function with the right signature into a get portfolio by Id handler
type GetPortfolioByIDHandlerFunc func(GetPortfolioByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPortfolioByIDHandlerFunc) Handle(params GetPortfolioByIDParams) middleware.Responder {
	return fn(params)
}

// GetPortfolioByIDHandler interface for that can handle valid get portfolio by Id params
type GetPortfolioByIDHandler interface {
	Handle(GetPortfolioByIDParams) middleware.Responder
}

// NewGetPortfolioByID creates a new http.Handler for the get portfolio by Id operation
func NewGetPortfolioByID(ctx *middleware.Context, handler GetPortfolioByIDHandler) *GetPortfolioByID {
	return &GetPortfolioByID{Context: ctx, Handler: handler}
}

/* GetPortfolioByID swagger:route GET /portfolios/{portfolioId} portfolios getPortfolioById

Find portfolio by ID

Returns a single portfolio

*/
type GetPortfolioByID struct {
	Context *middleware.Context
	Handler GetPortfolioByIDHandler
}

func (o *GetPortfolioByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPortfolioByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
