// Code generated by go-swagger; DO NOT EDIT.

package portfolios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/veremchukvv/stonks-test/models"
)

// GetPortfolioByIDOKCode is the HTTP code returned for type GetPortfolioByIDOK
const GetPortfolioByIDOKCode int = 200

/*GetPortfolioByIDOK successful operation

swagger:response getPortfolioByIdOK
*/
type GetPortfolioByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Portfolio `json:"body,omitempty"`
}

// NewGetPortfolioByIDOK creates GetPortfolioByIDOK with default headers values
func NewGetPortfolioByIDOK() *GetPortfolioByIDOK {

	return &GetPortfolioByIDOK{}
}

// WithPayload adds the payload to the get portfolio by Id o k response
func (o *GetPortfolioByIDOK) WithPayload(payload *models.Portfolio) *GetPortfolioByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio by Id o k response
func (o *GetPortfolioByIDOK) SetPayload(payload *models.Portfolio) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPortfolioByIDBadRequestCode is the HTTP code returned for type GetPortfolioByIDBadRequest
const GetPortfolioByIDBadRequestCode int = 400

/*GetPortfolioByIDBadRequest Invalid ID supplied

swagger:response getPortfolioByIdBadRequest
*/
type GetPortfolioByIDBadRequest struct {
}

// NewGetPortfolioByIDBadRequest creates GetPortfolioByIDBadRequest with default headers values
func NewGetPortfolioByIDBadRequest() *GetPortfolioByIDBadRequest {

	return &GetPortfolioByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetPortfolioByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetPortfolioByIDNotFoundCode is the HTTP code returned for type GetPortfolioByIDNotFound
const GetPortfolioByIDNotFoundCode int = 404

/*GetPortfolioByIDNotFound Portfolio not found

swagger:response getPortfolioByIdNotFound
*/
type GetPortfolioByIDNotFound struct {
}

// NewGetPortfolioByIDNotFound creates GetPortfolioByIDNotFound with default headers values
func NewGetPortfolioByIDNotFound() *GetPortfolioByIDNotFound {

	return &GetPortfolioByIDNotFound{}
}

// WriteResponse to the client
func (o *GetPortfolioByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
