// Code generated by go-swagger; DO NOT EDIT.

package portfolios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePortfolioBadRequestCode is the HTTP code returned for type UpdatePortfolioBadRequest
const UpdatePortfolioBadRequestCode int = 400

/*UpdatePortfolioBadRequest Invalid ID supplied

swagger:response updatePortfolioBadRequest
*/
type UpdatePortfolioBadRequest struct {
}

// NewUpdatePortfolioBadRequest creates UpdatePortfolioBadRequest with default headers values
func NewUpdatePortfolioBadRequest() *UpdatePortfolioBadRequest {

	return &UpdatePortfolioBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePortfolioBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePortfolioNotFoundCode is the HTTP code returned for type UpdatePortfolioNotFound
const UpdatePortfolioNotFoundCode int = 404

/*UpdatePortfolioNotFound Portfolio not found

swagger:response updatePortfolioNotFound
*/
type UpdatePortfolioNotFound struct {
}

// NewUpdatePortfolioNotFound creates UpdatePortfolioNotFound with default headers values
func NewUpdatePortfolioNotFound() *UpdatePortfolioNotFound {

	return &UpdatePortfolioNotFound{}
}

// WriteResponse to the client
func (o *UpdatePortfolioNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdatePortfolioMethodNotAllowedCode is the HTTP code returned for type UpdatePortfolioMethodNotAllowed
const UpdatePortfolioMethodNotAllowedCode int = 405

/*UpdatePortfolioMethodNotAllowed Validation exception

swagger:response updatePortfolioMethodNotAllowed
*/
type UpdatePortfolioMethodNotAllowed struct {
}

// NewUpdatePortfolioMethodNotAllowed creates UpdatePortfolioMethodNotAllowed with default headers values
func NewUpdatePortfolioMethodNotAllowed() *UpdatePortfolioMethodNotAllowed {

	return &UpdatePortfolioMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePortfolioMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
