// Code generated by go-swagger; DO NOT EDIT.

package stocks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStocksHandlerFunc turns a function with the right signature into a get stocks handler
type GetStocksHandlerFunc func(GetStocksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStocksHandlerFunc) Handle(params GetStocksParams) middleware.Responder {
	return fn(params)
}

// GetStocksHandler interface for that can handle valid get stocks params
type GetStocksHandler interface {
	Handle(GetStocksParams) middleware.Responder
}

// NewGetStocks creates a new http.Handler for the get stocks operation
func NewGetStocks(ctx *middleware.Context, handler GetStocksHandler) *GetStocks {
	return &GetStocks{Context: ctx, Handler: handler}
}

/* GetStocks swagger:route GET /stocks stocks getStocks

Get information sbout stock

*/
type GetStocks struct {
	Context *middleware.Context
	Handler GetStocksHandler
}

func (o *GetStocks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStocksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
