// Code generated by go-swagger; DO NOT EDIT.

package stocks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostStocksBadRequestCode is the HTTP code returned for type PostStocksBadRequest
const PostStocksBadRequestCode int = 400

/*PostStocksBadRequest General error

swagger:response postStocksBadRequest
*/
type PostStocksBadRequest struct {
}

// NewPostStocksBadRequest creates PostStocksBadRequest with default headers values
func NewPostStocksBadRequest() *PostStocksBadRequest {

	return &PostStocksBadRequest{}
}

// WriteResponse to the client
func (o *PostStocksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostStocksNotFoundCode is the HTTP code returned for type PostStocksNotFound
const PostStocksNotFoundCode int = 404

/*PostStocksNotFound Stocks not found

swagger:response postStocksNotFound
*/
type PostStocksNotFound struct {
}

// NewPostStocksNotFound creates PostStocksNotFound with default headers values
func NewPostStocksNotFound() *PostStocksNotFound {

	return &PostStocksNotFound{}
}

// WriteResponse to the client
func (o *PostStocksNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostStocksMethodNotAllowedCode is the HTTP code returned for type PostStocksMethodNotAllowed
const PostStocksMethodNotAllowedCode int = 405

/*PostStocksMethodNotAllowed Invalid input

swagger:response postStocksMethodNotAllowed
*/
type PostStocksMethodNotAllowed struct {
}

// NewPostStocksMethodNotAllowed creates PostStocksMethodNotAllowed with default headers values
func NewPostStocksMethodNotAllowed() *PostStocksMethodNotAllowed {

	return &PostStocksMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostStocksMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
