// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateProfileOKCode is the HTTP code returned for type CreateProfileOK
const CreateProfileOKCode int = 200

/*CreateProfileOK successful operation

swagger:response createProfileOK
*/
type CreateProfileOK struct {
}

// NewCreateProfileOK creates CreateProfileOK with default headers values
func NewCreateProfileOK() *CreateProfileOK {

	return &CreateProfileOK{}
}

// WriteResponse to the client
func (o *CreateProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
