// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LogoutUserOKCode is the HTTP code returned for type LogoutUserOK
const LogoutUserOKCode int = 200

/*LogoutUserOK successful operation

swagger:response logoutUserOK
*/
type LogoutUserOK struct {
}

// NewLogoutUserOK creates LogoutUserOK with default headers values
func NewLogoutUserOK() *LogoutUserOK {

	return &LogoutUserOK{}
}

// WriteResponse to the client
func (o *LogoutUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
