---
server:
  port: "8000"
  shutdown_timeout: 5000000000
  # 5000000000 = 5 seconds
  cors:
    - "http://127.0.0.1:3000"
    - "http://localhost:3000"

client_server:
  client_port: "8001"

oauth:
  vk_client_id: ""
  vk_client_secret: ""
  vk_redirect_url: ""
  google_client_id: ""
  google_client_secret: ""
  google_redirect_url: ""

db:
  url: ""

