swagger: "2.0"
info:
  description: "This is a Stonks service. You can find out more about us at [https://github.com/veremchukvv/stonks-test](https://github.com/veremchukvv/stonks-test)."
  version: "1.0.0"
  title: "Stonks"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/mit-license.php"
schemes:
  - "http"
basePath: "/"
tags:
  - name: "users"
    description: "Operations about authorization"
  - name: "profile"
    description: "Operations about user"
  - name: "portfolios"
    description: "Operations about portfolio"
  - name: "market"
    description: "Operations about stocks"
paths:
  /signup:
    post:
      tags:
        - "users"
      summary: "Create new user into the system"
      description: ""
      operationId: "CreateUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/CreateUserRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateUserResponse"
        "400":
          description: ""
        "401":
          description: ""
  /signin:
    post:
      tags:
        - "users"
      summary: "Log user into the system"
      description: ""
      operationId: "loginUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: "OAuth general error"
        "401":
          description: "Unauthorized"
  /signout:
    post:
      tags:
        - "users"
      summary: "Log out current user"
      description: ""
      operationId: "logoutUser"
      produces:
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
  /api/v1/profile:
    post:
      tags:
        - "profile"
      summary: "Create new profile"
      description: ""
      operationId: "createProfile"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/CreateProfile"
      responses:
        "200":
          description: "successful operation"
    put:
      tags:
        - "profile"
      summary: "Update profile"
      description: ""
      operationId: "updateProfile"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/UpdateProfile"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Profile update general error"
    get:
      tags:
        - "profile"
      responses:
        "200":
          description: "successful operation"
  /api/v1/portfolios:
    post:
      tags:
        - "portfolios"
      summary: "Create new portfolio"
      operationId: "addNewPortfolio"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "New portfolio object that needs to be added to profile"
          required: true
          schema:
            $ref: "#/definitions/CreatePortfolioReq"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Portfolio"
        "405":
          description: "Invalid input"
    put:
      tags:
        - "portfolios"
      summary: "Update an existing portfolio"
      description: ""
      operationId: "updatePortfolio"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Update portfolio object"
          required: true
          schema:
            $ref: "#/definitions/UpdatePortfolioReq"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Portfolio"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Portfolio not found"
        "405":
          description: "Validation exception"
  /api/v1/portfolios/{portfolioId}:
    get:
      tags:
        - "portfolios"
      summary: "Find portfolio by ID"
      description: "Returns a single portfolio"
      operationId: "getPortfolioById"
      produces:
        - "application/json"
      parameters:
        - name: "portfolioId"
          in: "path"
          description: "ID of portfolio to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Portfolio"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Portfolio not found"
    delete:
      tags:
        - "portfolios"
      summary: "Delete a portfolio"
      description: ""
      operationId: "deletePortfolio"
      produces:
        - "application/json"
      parameters:
        - name: "portfolioId"
          in: "path"
          description: "Portfolio id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Portfolio not found"
  /api/v1/market/stocks:
    get:
      tags:
        - "market"
      summary: "Get information about stocks"
      description: ""
      operationId: "getStocks"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Stocks to search"
          schema:
            $ref: "#/definitions/Search"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Stock"
        "405":
          description: "Invalid input"
        "404":
          description: "Stocks not found"
  /api/v1/market/deals:
    post:
      tags:
        - "market"
      summary: "Add deal"
      description: ""
      operationId: "addDeal"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Deal to add"
          schema:
            $ref: "#/definitions/Deal"
      responses:
        "400":
          description: "General error"
        "405":
          description: "Invalid input"
        "404":
          description: ""
definitions:
  LoginRequest:
    type: "object"
    properties:
      JWT:
        type: "string"
  LoginResponse:
    type: "object"
    properties:
      JWT:
        type: "string"
  CreateProfile:
    type: "object"
    properties:
      JWT:
        type: "string"
  UpdateProfile:
    type: "object"
    properties:
      username:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
  CreatePortfolioReq:
    type: "object"
    properties:
      name:
        type: "string"
      public:
        type: "boolean"
        default: false
  UpdatePortfolioReq:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      public:
        type: "boolean"
  Portfolio:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      public:
        type: "boolean"
        default: false
      stocks:
        type: "array"
        items:
          $ref: "#/definitions/Stock"
      cash:
        type: "number"
        format: "float"
  Stock:
    type: "object"
    properties:
      id:
        type: "string"
        description: "ticker"
      name:
        type: "string"
        description: "name of stock"
      summary:
        type: "string"
        description: "info about the stock"
      type:
        type: "string"
        enum: [bond, stock, fund]
      cost:
        type: "number"
        format: "float"
      currency:
        type: "string"
        enum: [usd, eur, rub]
  Search:
    type: "string"
    description: "search string"
  Deal:
    type: "object"
    properties:
      id:
        type: "number"
        format: "int64"
        description: "id of deal"
      type:
        type: "string"
        enum: [buy, sell]
        description: "type of deal"
      lot:
        type: "string"
        description: "ticker"
      quantity:
        type: "number"
        format: "int64"