// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateProfile create profile
//
// swagger:model CreateProfile
type CreateProfile struct {

	// j w t
	JWT string `json:"JWT,omitempty"`
}

// Validate validates this create profile
func (m *CreateProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create profile based on context it is used
func (m *CreateProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProfile) UnmarshalBinary(b []byte) error {
	var res CreateProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
