// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Portfolio portfolio
//
// swagger:model Portfolio
type Portfolio struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// public
	Public bool `json:"public,omitempty"`

	// stocks
	Stocks []*Stock `json:"stocks"`
}

// Validate validates this portfolio
func (m *Portfolio) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStocks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Portfolio) validateStocks(formats strfmt.Registry) error {
	if swag.IsZero(m.Stocks) { // not required
		return nil
	}

	for i := 0; i < len(m.Stocks); i++ {
		if swag.IsZero(m.Stocks[i]) { // not required
			continue
		}

		if m.Stocks[i] != nil {
			if err := m.Stocks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stocks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this portfolio based on the context it is used
func (m *Portfolio) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStocks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Portfolio) contextValidateStocks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stocks); i++ {

		if m.Stocks[i] != nil {
			if err := m.Stocks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stocks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Portfolio) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Portfolio) UnmarshalBinary(b []byte) error {
	var res Portfolio
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
