// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateProfile update profile
//
// swagger:model UpdateProfile
type UpdateProfile struct {

	// j w t
	JWT string `json:"JWT,omitempty"`
}

// Validate validates this update profile
func (m *UpdateProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update profile based on context it is used
func (m *UpdateProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateProfile) UnmarshalBinary(b []byte) error {
	var res UpdateProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
